
package cn.itcast.export.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EpServiceService", targetNamespace = "http://webservice.export.itcast.cn/", wsdlLocation = "http://localhost:8080/export_system/ws/export?wsdl")
public class EpServiceService
    extends Service
{

    private final static URL EPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EPSERVICESERVICE_EXCEPTION;
    private final static QName EPSERVICESERVICE_QNAME = new QName("http://webservice.export.itcast.cn/", "EpServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/export_system/ws/export?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPSERVICESERVICE_WSDL_LOCATION = url;
        EPSERVICESERVICE_EXCEPTION = e;
    }

    public EpServiceService() {
        super(__getWsdlLocation(), EPSERVICESERVICE_QNAME);
    }

    public EpServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPSERVICESERVICE_QNAME, features);
    }

    public EpServiceService(URL wsdlLocation) {
        super(wsdlLocation, EPSERVICESERVICE_QNAME);
    }

    public EpServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPSERVICESERVICE_QNAME, features);
    }

    public EpServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEpService
     */
    @WebEndpoint(name = "EpServicePort")
    public IEpService getEpServicePort() {
        return super.getPort(new QName("http://webservice.export.itcast.cn/", "EpServicePort"), IEpService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEpService
     */
    @WebEndpoint(name = "EpServicePort")
    public IEpService getEpServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.export.itcast.cn/", "EpServicePort"), IEpService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPSERVICESERVICE_EXCEPTION!= null) {
            throw EPSERVICESERVICE_EXCEPTION;
        }
        return EPSERVICESERVICE_WSDL_LOCATION;
    }

}
